### ISSUE TITLE
App crashes after looking through about three to four images.

### ISSUE THREAD

**Issue by CorWilson** [ahodesuka/ahoviewer#111]
When I clicked on up to three or four images, the application crashes. In the event viewer, it reads:

> Faulting application name: ahoviewer.exe, version: 0.0.0.0, time stamp: 0x00000000
> Faulting module name: libgdk_pixbuf-2.0-0.dll, version: 2.32.3.0, time stamp: 0x00000000
> Exception code: 0xc0000005
> Fault offset: 0x000000000000f913
> Faulting process id: 0x1178
> Faulting application start time: 0x01d6bddd92ba6226
> Faulting application path: F:\Utilities\ahoviewer\ahoviewer.exe
> Faulting module path: F:\Utilities\ahoviewer\libgdk_pixbuf-2.0-0.dll
> Report Id: ab14a79c-f83a-4cf4-a2a4-f59583566c22
> Faulting package full name: 
> Faulting package-relative application ID: 

This is on Windows 10.

**Comment by ahodesuka** [comment]
ahoviewer on Windows is generally buggy and I can't really support it at the moment.
A big problem with the latest (nearly 2 years old) Windows release is that it's packaged with a bunch of libraries - some of which are long outdated and had bugs in them.  Seeing as the crash is occurring because of one of those (libgdk_pixbuf-2.0-0.dll) is all I can really go off.

I have used it on Windows quite a bit, and have noticed the animated GIFs usually cause problems when using the booru browser, which might be what you're experiencing or some other kind of issue when displaying loading images in the booru browser.
