### ISSUE TITLE
Tbib / Sankaku Complex

### ISSUE THREAD

**Issue by fhawkes123** [ahodesuka/ahoviewer#121]
i have some issues with tbib.org, Some images do not show the preview, just clicking on the image to see whats is
 http://i.prntscr.com/BgZJeRANRaijTp8EXpSgAg.png
 
 -
 
 and please, make a easy way to puting the idol.sankakucomplex.com and chan.sankakucomplex.com on the ahoviwer

**Comment by ahodesuka** [comment]
efd239a072f2c8dfc241e71785a7f709a79936b2 Should fix the problem on tbib.org

But since you're using Windows you'll have to wait for a new build to come out.
I'm working on a action that will compile and upload a portable Windows build after every commit.

As for the sankaku support, chan.sankakucomplex.com is supported via a [plugin](https://github.com/ahodesuka/ahoviewer-plugins/tree/master/sankakucomplex), you have to
enter `https://capi-v2.sankakucomplex.com` as the url when adding it since that's the API url.
idol.sankakucomplex.com is not currently supported because it has no public API.
