### ISSUE TITLE
Hard drive space gone

### ISSUE THREAD

**Issue by wickedwzrd** [ahodesuka/ahoviewer#39]
It might not have been ahoviewer that caused this problem but I'm fairly certain it was. I was running ncmpcpp and ahoviewer, then I started to scroll through the pictures quickly and noticed that some errors kept popping up in my terminal. Then my computer slowed down and said I was running out of space. It went from around 20Gb to nothing in a couple min. After force shutting down it was fixed but I just wanted to put this here just in case it was ahoviewer that caused this.
This was the error:
(ahoviewer:1769): glibmm-CRITICAL **: bool Glib::DispatchNotifier::pipe_io_handler(Glib::IOCondition): assertion 'data.notifier == this' failed
Also just so you know I'm using osx and version 1.4.4-11-ge05df9e for ahoviewer.

**Comment by ahodesuka** [comment]
You should recompile with the latest master (1.4.6) since I fixed a crash that may cause this problem.

Ahoviewer stores all of it's temporary files in `/tmp` or something similar.
If the program crashes it will not clean up after itself, and you will have to do it manually by deleting the ahoviewer.XXXXX directories.
Closing a booru tab does not delete the images that were viewed, only when the program exits normally are they deleted.  This is to lessen the amount of bandwidth used.
