### ISSUE TITLE
Bash on Windows10 ahoviewer?

### ISSUE THREAD

**Issue by Suushi** [ahodesuka/ahoviewer#48]
how would one install ahoviewer, but in bash within windows10?

**Comment by ahodesuka** [comment]
Why not just use the native binary for windows?

**Comment by XenosisReaper** [comment]
To come back to this, I just tried it on bash on ubuntu on windows but can't get past ./bootstrap

`autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
version.sh: 24: version.sh: [[: not found
version.sh: 24: version.sh: -f: not found
version.sh: 24: version.sh: [[: not found
version.sh: 24: version.sh: -f: not found
autoreconf: configure.ac: tracing
version.sh: 24: version.sh: [[: not found
version.sh: 24: version.sh: -f: not found
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
version.sh: 24: version.sh: [[: not found
version.sh: 24: version.sh: -f: not found
configure.ac:36: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1`

Was trying it out since there isn't a fixed windows release
