### ISSUE TITLE
[Win10] Ahoviewer launches minimized and stays minimized

### ISSUE THREAD

**Issue by Atulin** [ahodesuka/ahoviewer#73]
Basically, what the title says.

I tried updating to the newest release, no cigar. I tried uninstalling and installing the newest release – no cigar.
When hovering over the icon on taskbar I can see the miniature of the window, but when hovering over the miniature it simply shows my uncovered desktop.

Edit: Uninstalled it again, with Revo, deleted both registry keys, all files in appdata, every single trace of Ahoviewer on my disk. Installed it again. The UI isis broken, it seems.
![image](https://user-images.githubusercontent.com/11233299/47251799-50e1cd80-d439-11e8-87a7-8f77ff4b0f39.png)

**Comment by ahodesuka** [comment]
Open `%LOCALAPPDATA%/ahoviewer/ahoviewer.cfg` and set the `x = #` and `y = #` to 0.
There was a problem in an older version that would save those values to `-32000` and cause ahoviewer to never appear on your screen again until you edit the config as described above.
The bug has been fixed since version 1.6.0.

**Comment by Atulin** [comment]
The entire ahoviewer appdata folder was nuked. Only then I installed the newest available release. Screenshot in my opening post shows the result.
