### ISSUE TITLE
Mouse keybind support?

### ISSUE THREAD

**Issue by zhuayun** [ahodesuka/ahoviewer#80]
i'd like to use (or have the option to use) the mouse wheel to zoom in and out. or just mouse button support for the keybindings menu at all. Other binds I would personally use would be like how left click goes to the next image, right click goes back an image.

**Comment by ahodesuka** [comment]
Ctrl+Mousewheel will do the zoom in/out.  Note that the zoom mode has to be set to manual for zoom to work.
Left click by default will navigate to the next image, but if you enable the `Smart mouse navigation` option in the settings it will make it so that left clicking on the left side of the image will go backwards and left clicking on the right side will go forward.

Not having mouse button support in the keybinding settings is a limitation in GTK+, and there isn't much I can do to easily get around it.

**Comment by zhuayun** [comment]
ah i see, well i appreciate the quick reply and explanation. but i've tried setting ctrl + mouse wheel but it just sits on "New accelerator.." while i spam ctrl + mousewheel up/down. I'm trying on both win10 and arch linux.
